/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmi;

import java.awt.Color;

/**
 *
 * @author vaishu
 */
public class Bmi_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Bmi_Interface
     */
    public Bmi_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_bmiIndicator = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        btn_Calculate = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        txt_bmi = new javax.swing.JTextField();
        txt_h = new javax.swing.JTextField();
        txt_w = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Body Mass Index Calculator");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 400, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 140));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bmiIndicator.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jPanel4.add(lbl_bmiIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 260, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Weight (kg) :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(" Height (cm) :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("BMI");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        btn_Exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        btn_Calculate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Calculate.setText("Calculate");
        btn_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalculateActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        btn_Clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        txt_bmi.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jPanel4.add(txt_bmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, 40));

        txt_h.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hActionPerformed(evt);
            }
        });
        jPanel4.add(txt_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 250, 40));

        txt_w.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(txt_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 250, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 590, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\BMI\\src\\main\\java\\bmi\\image\\bmi-calaculator.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

       System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
     txt_h.setText("");  
     txt_w.setText(""); 
     txt_bmi.setText(""); 
     txt_bmi.setOpaque(true);
     txt_bmi.setBackground(null);
     lbl_bmiIndicator.setText("");

  // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalculateActionPerformed
        // TODO add your handling code here:
        double height = Double.parseDouble(txt_h.getText());
        double weight = Double.parseDouble(txt_w.getText());
        
        //double BMI = w / (h *h);
        double BMI =  (( 100 * 100 * weight ) / ( height * height ));
        // multiplying 100 * 100 to convert cm to m
    
      
        
        String cal = String.format("%.2f",BMI);
        
        txt_bmi.setText(cal);
        
        if(BMI <= 18.5)
        {
            txt_bmi.setOpaque(true);
            txt_bmi.setBackground(Color.BLUE);
            lbl_bmiIndicator.setBackground(Color.BLUE);
            lbl_bmiIndicator.setForeground(Color.BLUE);
            lbl_bmiIndicator.setText("UnderWeight");
           // lbl__BMI1.setForeground(Color.blue);
           
            
         }
        else if(BMI <= 24.5)    
        {
            
            
            txt_bmi.setOpaque(true);
            txt_bmi.setBackground(Color.GREEN);
             lbl_bmiIndicator.setBackground(Color.GREEN);
            lbl_bmiIndicator.setForeground(Color.GREEN);
            lbl_bmiIndicator.setText("Normal Weight");
        }
        else if(BMI <= 29.5)    
        {
            txt_bmi.setOpaque(true);
            txt_bmi.setBackground(Color.ORANGE);
             lbl_bmiIndicator.setBackground(Color.ORANGE);
            lbl_bmiIndicator.setForeground(Color.ORANGE);
            lbl_bmiIndicator.setText("Over Weight");
        }
        else if(BMI >= 30)    
        {
            txt_bmi.setOpaque(true);
            txt_bmi.setBackground(Color.RED);
             lbl_bmiIndicator.setBackground(Color.RED);
            lbl_bmiIndicator.setForeground(Color.RED);
            lbl_bmiIndicator.setText("Obese Weight");
        }
        
        
    }//GEN-LAST:event_btn_CalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bmi_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bmi_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bmi_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bmi_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bmi_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calculate;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_bmiIndicator;
    private javax.swing.JTextField txt_bmi;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_w;
    // End of variables declaration//GEN-END:variables
}
